baseURL = "http://books.jcarreras.es/"
languageCode = "en-us"
title = "List of books I have read"
theme = "hugo-swift-theme"
paginate = 52

[Author]
    name = "Jan Carreras"

[params]
  author = "Jan Carreras"
